spring:
  freemarker:
    cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.tsxygfy.beyond.*: debug
  # file: ./log/beyond-log.log
# 设置域名
#beyond:
#  domain: www.tsxygfy.cn
